### ISSUE TITLE
form is responsive but ui is not much eye pleasing image link might broken

### ISSUE THREAD

**Issue by warisamir** [Gaurav-Verma07/sampark#10]
![image](https://github.com/Gaurav-Verma07/sampark/assets/77074869/be8d8615-c776-4cbe-a8f0-7bbb610c959a)
i would like to make this much pleasant for sampark foundation 
Also images are broken and their link night not working becoz they are on website itself rather on any cloud platform i would like to put these thing simple and work on it 
![image](https://github.com/Gaurav-Verma07/sampark/assets/77074869/27ffec32-e135-403b-9341-17410a322fed)
![image](https://github.com/Gaurav-Verma07/sampark/assets/77074869/1f9cee22-07e0-40b5-b12a-ceadbeea764c)

**Comment by warisamir** [comment]
please assgin me this issue as part of gssoc 23

**Comment by vk20july** [comment]
I want to work on this issue under gssoc'23 @Gaurav-Verma07 sir

**Comment by Gaurav-Verma07** [comment]
you're already assigned bro
