### ISSUE TITLE
I want to add phone number field in the contact form

### ISSUE THREAD

**Issue by bhaskarkumar1** [Gaurav-Verma07/sampark#102]
I want to add phone number field as  it is not present in the contact form. please check the attached screenshot below.
![Screenshot_20230608_021233](https://github.com/Gaurav-Verma07/sampark/assets/84345649/800da20a-adbd-4d94-a431-a84494f94cdd)

**Comment by Gaurav-Verma07** [comment]
It's not required

**Comment by bhaskarkumar1** [comment]
ok
