### ISSUE TITLE
Improving the UI of "Our Values" segment

### ISSUE THREAD

**Issue by harshita-kaushik2** [Gaurav-Verma07/sampark#11]
Due to the inconsistent padding and card styling, the UI of the page requires improvement. 
I would love to work on this issue and hence request you to assign it to me as a GSSoC 2023 contributor. 
Thank You :)

**Comment by abhi03ruchi** [comment]
I would like to work on this issue. 
 I will add parallax flipping cards to enhance the UI. 
 Plz assign this task to me under gssoc'23.

https://github.com/Gaurav-Verma07/sampark/assets/105661636/c4148c14-cc19-47fb-bac6-9e0a2a55b8b1
