### ISSUE TITLE
Add a "Scroll to Top" floating button

### ISSUE THREAD

**Issue by harshita-kaushik2** [Gaurav-Verma07/sampark#12]
Hey,
As one can observe from viewing the website, it lacks a scroll-to-top button. Adding this floating button would enhance the user experience of the website.

I'd love to contribute this feature as I have past experience of creating in my personal projects and would request you to assign this issue to me as GSSoC 2023 Contributor.
Thank You :)

**Comment by UditSharma9999** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.
