### ISSUE TITLE
Feat: Workflow to greet when new issue/pull request opens

### ISSUE THREAD

**Issue by harmeetsingh11** [Gaurav-Verma07/sampark#120]
## Description
Currently, this project does not have any action to greet to contributors. Github action is the great tool to automate the manual stuff for your project. I would like to create Github Action workflow to greet to the new PR and issue creator.

## Record
- [x] I agree to follow Contributing guidelines and Code of conduct of this project.
- [x] I am a GSSoC'23 Contributor.

Please assign me this issue under GSSoC'23
Thanks

**Comment by Nishitbaria** [comment]
Hey @harmeetsingh11  I am Already Created Isuue on that: https://github.com/Gaurav-Verma07/sampark/issues/82
