### ISSUE TITLE
improve the navbar

### ISSUE THREAD

**Issue by karthiknadar1204** [Gaurav-Verma07/sampark#129]
### Description

In the current navbar, the contents seem to be crouched in the centre, in my proposed solution, I wish to make the navbar links to be on the left side and add some more spacing to them and the logo to the left.
Furthermore, I will be adding some hover effects to the link.
Lastly, I will be making the navbar sticky and the container in which the navbar links and logo are, I will make it translucent with some box shadow to make it look prominent.

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by Gaurav-Verma07** [comment]
good approach bro, but its already in progress
