### ISSUE TITLE
Adding Hover animations in the navbar

### ISSUE THREAD

**Issue by Anshika-Jain02** [Gaurav-Verma07/sampark#151]
*We can add hover animations like a running line etc in the navbar to improve the overall appearance of the website.*

![image](https://github.com/Gaurav-Verma07/sampark/assets/104912087/a1bd2a3c-cd5d-4461-bdb6-a3242f359538)

@Gaurav-Verma07 please assign me this issue under gssoc'23

**Comment by sagarb2003** [comment]
Hey @Gaurav-Verma07 Plz assign me this issue under GSSOC'23
