### ISSUE TITLE
Enhance UI of the FAQ section

### ISSUE THREAD

**Issue by Pragati-3003** [Gaurav-Verma07/sampark#172]
### Description

I would like to change the UI of the FAQ section of the website by adding some cool effects .
So,please assign this issue to me under gssoc'23.

### Screenshots

![Screenshot 2023-06-22 233559](https://github.com/Gaurav-Verma07/sampark/assets/132778037/d7d59831-a339-43ff-aa3b-116f249abae8)

**Comment by Gaurav-Verma07** [comment]
Make it look like as in https://task-management-snowy-kappa.vercel.app/
use green themed color on hover.

**Comment by Gaurav-Verma07** [comment]
use rubik font

**Comment by Pragati-3003** [comment]
> Make it look like as in https://task-management-snowy-kappa.vercel.app/ use green themed color on hover.

okie
