### ISSUE TITLE
Contact us link not working

### ISSUE THREAD

**Issue by k-deepak04** [Gaurav-Verma07/sampark#186]
### Description

the mail link provided in contact us is not clickable and working also the number 
i wold like to make it such that if one clicks on email-id his/her gmail should open 
similarly for phone number

### Screenshots

![image](https://github.com/Gaurav-Verma07/sampark/assets/96341431/260619fa-6f0a-4153-8860-fdb57d8c05b6)

**Comment by k-deepak04** [comment]
@Gaurav-Verma07 also if this is dummy mail
i would suggest you to create one gmail for this project as we will require one mail for many purpose for creating account further like database,mails etc dependencies we use

can give the new mail if this one is dummy i'll integrate that also 
Thanks :)

**Comment by Gaurav-Verma07** [comment]
the project is in initial phase, its just dummy data...

**Comment by k-deepak04** [comment]
okay bro
