### ISSUE TITLE
Change login page design

### ISSUE THREAD

**Issue by sabhisharma-ise** [Gaurav-Verma07/sampark#20]
Changes that could be made to the login page:

- Use a more modern and stylish design.
- Use a simpler layout with less clutter.
- Use larger fonts and easier-to-read text.

By making these changes to the login page, we can make it more user-friendly and inviting.

![image](https://github.com/Gaurav-Verma07/sampark/assets/100849696/b9610d19-721d-407b-b823-84d3c89b9ce5)
| *Here is an example of a login page* |

**Comment by fatemaker254** [comment]
Hi, the above example you gave is quiet great and I would like to contribute on this issue. 
Pls assign me

**Comment by shreyal0007** [comment]
Hey i would love to work on the UI of the Sign In page and show my skills. Also i would make sure of its responsiveness.
kindly assign it to me under GSSOC 2023.
