### ISSUE TITLE
Broken Google Drive Link in Our Gallery Section

### ISSUE THREAD

**Issue by sabhisharma-ise** [Gaurav-Verma07/sampark#21]
The images in the 'Our Gallery' section of the Sampark website are not visible. The Google Drive link that is used to display the images is broken. This is preventing visitors from seeing the photos of the work that Sampark is doing to help orphaned children.

Possible Solutions:

- Fix the Google Drive link.
- Replace the Google Drive link with a different image hosting service

![image](https://github.com/Gaurav-Verma07/sampark/assets/100849696/c2eed715-07bf-451e-bb41-07177009b6df)
| *Our Gallery - Images are not visible* |

By following these tips, you can help Sampark fix the issue and make sure that visitors can see the photos of the work that they are doing to help orphaned children.

Please provide me with updated Photos for the Gallary, so I can fix this issue asap!

Contributor - Sabhi Sharma (GSSOC'23)

**Comment by Gaurav-Verma07** [comment]
This issue is already in progress
#2
