### ISSUE TITLE
Our work and Faq section ui improvement

### ISSUE THREAD

**Issue by SubhamB2003** [Gaurav-Verma07/sampark#228]
The current UI for both sections is not looking good both need some improvement

Read more about our work through our blogs... this portion also needs some UI improvement 
![image](https://github.com/Gaurav-Verma07/sampark/assets/94003231/65013151-a2d2-4d87-bf03-bf0f8359519d)

The text is not visible properly if I hover it then it's ok otherwise not
![image](https://github.com/Gaurav-Verma07/sampark/assets/94003231/a325e4e0-a7f1-4086-b207-e2568c6bb918)

**Comment by Gaurav-Verma07** [comment]
resolved
