### ISSUE TITLE
Sticky navbar

### ISSUE THREAD

**Issue by mandliyarajendra11** [Gaurav-Verma07/sampark#237]
A sticky navbar, also known as a fixed navbar or a persistent navbar, is a navigation menu or bar on a website that remains visible and fixed in its position as the user scrolls down the page. It stays "stuck" to the top or bottom of the browser window, providing continuous access to important navigation links or menu options

i want to work on this issue can you assign me this issue.

**Comment by Gaurav-Verma07** [comment]
not required
