### ISSUE TITLE
Update Sign in page

### ISSUE THREAD

**Issue by Ayushhgupta39** [Gaurav-Verma07/sampark#34]
I want to update the sign in form in the Sign-in page.
<img width="959" alt="image" src="https://github.com/Gaurav-Verma07/sampark/assets/96309609/bb369103-59c8-47d4-89fc-094701fa4813">
I want to improve the UI and design, so that it looks better like the rest of the project. Assign me this issue.

**Comment by Gaurav-Verma07** [comment]
In progress
