### ISSUE TITLE
[feature]: add contributors page ✨🚀

### ISSUE THREAD

**Issue by 0xabdulkhalid** [Gaurav-Verma07/sampark#345]
## Description
- To celebrate and acknowledge the valuable contributions from our community, we propose adding a dedicated "Contributors" page to the Sampark repository. 
- This page will showcase a list of all individuals who have contributed to the project, expressing our gratitude and highlighting their efforts.

## Key Points
1. The "Contributors" page will be accessible from the repository's main navigation, making it easily discoverable for all users and contributors.
2. The page will include a comprehensive list of contributors' names, along with their GitHub usernames or preferred identifiers.
3. Contributions will be recognized based on pull requests, issues, code reviews, and other meaningful contributions to the project.
4. The page will be automatically updated through automation or a maintainable process to ensure it remains up-to-date with the latest contributions.

## Expected Outcome
- By adding a "Contributors" page, we aim to foster a sense of community and appreciation among our contributors.
-  It will provide a public record of their involvement and dedication to the project, encouraging even more individuals to participate and contribute to Sampark.

**Comment by 0xabdulkhalid** [comment]
### Hey there @Gaurav-Verma07 👋🏻 

Please make sure to assign this issue to me to make the work done!

Let's move forward with creating this "Contributors" page to honor the efforts of our wonderful contributors and showcase the collaborative spirit of Sampark! 🎉🙌

**Comment by Gaurav-Verma07** [comment]
bro its not required.
