### ISSUE TITLE
Improve Overall UI of Authentication page and add more features

### ISSUE THREAD

**Issue by Santosh7017** [Gaurav-Verma07/sampark#36]
<img width="960" alt="image" src="https://github.com/Gaurav-Verma07/sampark/assets/73546536/a847a443-8e13-44f8-8b6a-33e360e00025">

Register and login page's UI can be improved . hence I want to improve look and feel of these pages.

I would like to work on this part of the website as a GSSOC contributer

**Comment by Gaurav-Verma07** [comment]
Already in progress
