### ISSUE TITLE
To make the project's README file more informative and user-friendly by adding detailed information and relevant images and screenshots.

### ISSUE THREAD

**Issue by Aanya9693** [Gaurav-Verma07/sampark#38]
Description:
The current README file of the project lacks detailed information about its purpose, features, and benefits, and does not include any images or screenshots to showcase its functionality. This makes it difficult for new users and contributors to understand the project and get started with it.

Goal:
The goal is to update the README file of the project to make it more informative and user-friendly. This will help attract more users and contributors, and make it easier for them to understand the project's purpose, features, and benefits. The updated README file will include detailed information about the project, as well as relevant images or screenshots to showcase its functionality.

Solution:
To achieve this goal, we will work on updating the README file of the project by adding more detailed information about its purpose, features, and benefits. We will also include relevant images or screenshots to showcase its functionality. The updated README file will be comprehensive and user-friendly, making it easier for new users and contributors to understand the project and get started with it.

Kindly assign this issue to me.

**Comment by Gaurav-Verma07** [comment]
Your approach looks good, please continue.

**Comment by Aanya9693** [comment]
Hey, i am not able to run your project on my system, I tried a lot but couldn't get out of it. After running I am just getting a blank white page but no error. So please help me so that I can solve this issue.
![WhatsApp Image 2023-05-25 at 11 07 27 PM](https://github.com/Gaurav-Verma07/sampark/assets/101557638/ad72f792-78f2-4af1-b08e-afaf2d81a5cc)
![WhatsApp Image 2023-05-25 at 11 06 40 PM](https://github.com/Gaurav-Verma07/sampark/assets/101557638/943a0531-de5a-4cbe-912d-00399ed1a218)
