### ISSUE TITLE
Feature - Improve UI of Gallery section, Map section and Contact Us section

### ISSUE THREAD

**Issue by RashakDude** [Gaurav-Verma07/sampark#39]
@Gaurav-Verma07 Would like to work on the improvement of Gallery section which allow automatic image transition removing the labor cost of adding buttons. Also would like to customize Contact Us section and make is center aligned and enhanced. Would also like to work on Map and make it horizontal.

Please assign me the issue.

**Comment by Gaurav-Verma07** [comment]
Already opened
