### ISSUE TITLE
Improve the sign in page GSSOC'23

### ISSUE THREAD

**Issue by karthiknadar1204** [Gaurav-Verma07/sampark#4]

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by pxiy-a** [comment]
I can improve the sign in page with better UI . Could you please assign me this issue?

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by abhinow01** [comment]
hey i would like to work on this issue and improve the sign in page , please assign this issue to me under gssoc'23

**Comment by tusharv01** [comment]
HI as a gssoc contributor as my alligned in this issue, Please assign me this issue and will provide you the solution as soon as possible @Gaurav-Verma07

**Comment by Gaurav-Verma07** [comment]
@karthiknadar1204 please also make sure, the logo is appearing on right side.
