### ISSUE TITLE
Improve tha navbar GSSOC'23

### ISSUE THREAD

**Issue by karthiknadar1204** [Gaurav-Verma07/sampark#5]
I was thinking of making the background behind the navbar blur or we can create a container which contains all the links

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by pxiy-a** [comment]
I would like to work on this issue, this alligns with my tech stack. Could please assign me with this issue?

**Comment by adityavpawar** [comment]
I would like to work on this issue, my skill set is related to this stack. Could please assign me with this issue?

**Comment by karthiknadar1204** [comment]
@Gaurav-Verma07 I tried running the project on my local machine but on localhost 5173,i am getting a completely blank screen
<img width="1792" alt="Screenshot 2023-05-21 at 12 03 02 PM" src="https://github.com/Gaurav-Verma07/sampark/assets/95973644/460c61ab-171e-44e1-b8ea-4a00fe102
<img width="1451" alt="Screenshot 2023-05-21 at 12 04 35 PM" src="https://github.com/Gaurav-Verma07/sampark/assets/95973644/a5f1a5fa-4399-49e0-869a-8c3c3d466233">
e3b">

How do i proceed

**Comment by karthiknadar1204** [comment]
<img width="1792" alt="Screenshot 2023-05-21 at 12 03 02 PM" src="https://github.com/Gaurav-Verma07/sampark/assets/95973644/68581613-a1ce-4d67-8aeb-c5487b1700de">

**Comment by karthiknadar1204** [comment]
@Gaurav-Verma07 Tried it again but still not working,i m using mc operating system just in case

**Comment by Gaurav-Verma07** [comment]
Share the ss of console panel
