### ISSUE TITLE
Add smooth scroll option GSSOC'23

### ISSUE THREAD

**Issue by karthiknadar1204** [Gaurav-Verma07/sampark#6]
When clicking on the navbar links,instead of directly being showed the respective section,we can add a feature to scroll smoothly

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by JatinBisht2308** [comment]
@adityavpawar bhyiiii khud ke bana le

**Comment by UditSharma9999** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.

**Comment by karthiknadar1204** [comment]
Thank you
