### ISSUE TITLE
Page : Our values card UI enhancement 

### ISSUE THREAD

**Issue by Hemant2335** [Gaurav-Verma07/sampark#86]
The UI of the current card doesn't seems to be very pleasant , so I would like to

-> Add a entirely new layout to cards
-> add some hover effect
-> Also it doesn't match with the current theme so change that too

therefore please assign this task to me  under GSSOC'23

Thank you

Attached SS
![Screenshot (109)](https://github.com/Gaurav-Verma07/sampark/assets/85656999/1ebce4f0-b840-42c4-8640-57e07d8f8c75)

**Comment by Gaurav-Verma07** [comment]
already in progress
