### ISSUE TITLE
map section is not responsive for mobile view

### ISSUE THREAD

**Issue by 007xylogramori** [Gaurav-Verma07/sampark#9]
I would like to work on this issue as a part of Gssoc'23

![Screenshot (125)](https://github.com/Gaurav-Verma07/sampark/assets/119863801/012cb698-0a07-4bda-b2f2-d5be38b54268)

**Comment by RishabhJain0721** [comment]
Alright, you can work on this.

**Comment by 007xylogramori** [comment]
hey @RishabhJain0721  Can you please provide me with more details about how to setup the project on my machine locally.
The content of the readme is not sufficient. 
![Screenshot (133)](https://github.com/Gaurav-Verma07/sampark/assets/119863801/5f9f3946-a583-45c9-81de-eaf77041cb1b)

**Comment by 007xylogramori** [comment]
@Gaurav-Verma07 can you help me with how to configure .env file for the project setup in my machine locally

**Comment by Gaurav-Verma07** [comment]
mail me, I'll share env
