### ISSUE TITLE
[Feat]: Make a separate page for all blogs

### ISSUE THREAD

**Issue by suzy-g38** [Gaurav-Verma07/sampark#91]
Currently, we can see the blogs on the main home page, I would like to make an entirely separate page for blogs and by clicking on the main page's blog section, like "see more blogs" or something like that it will lead you to the blog page, where we can see them in a more clear format.

I would like to work on it under GSSOC'23

**Comment by Gaurav-Verma07** [comment]
sure, please refer mantineUI docs- https://ui.mantine.dev/category/article-cards
