### ISSUE TITLE
Adding feature: FAQ Section on homepage answering questions

### ISSUE THREAD

**Issue by amanagnihotri1** [Gaurav-Verma07/sampark#93]
Implementation- Adding multiple accordions answering repetitive questions 
Can i work on this under GSSOC 2023?

**Comment by Gaurav-Verma07** [comment]
sure, 
use the sample design from mantineUI to continue.
https://ui.mantine.dev/component/faq-simple

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign
